export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_FAIL = 'ADDUSER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const GET_VEHICLES = 'GET_VEHICLES';
export const GET_VEHICLES_FAIL = 'GET_VEHICLES_FAIL';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const ADD_VEHICLE_FAIL = 'ADD_VEHICLE_FAIL';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';
export const DELETE_VEHICLE_FAIL = 'DELETE_VEHICLE_FAIL';
export const REQUEST_USER_VEHICLES = 'REQUEST_USER_VEHICLES';
export const RECEIVE_USER_VEHICLES = 'RECEIVE_USER_VEHICLES';
export const RECEIVE_USER_FILTERS = 'RECEIVE_USER_FILTERS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_POST_PER_PAGE = 'SET_POST_PER_PAGE';
export const SELECT_MAKE = 'SELECT_MAKE';
export const SELECT_VEHICLE_MODEL = 'SELECT_VEHICLE_MODEL';
export const SELECT_YEAR = 'SELECT_YEAR';
export const SELECT_PRICE = 'SELECT_PRICE';
export const SELECT_MILEAGE = 'SELECT_MILEAGE';
export const REMOVE_MAKE = 'REMOVE_MAKE';
export const REMOVE_VEHICLE_MODEL = 'REMOVE_VEHICLE_MODEL';
export const REMOVE_YEAR = 'REMOVE_YEAR';
export const REMOVE_PRICE_MIN = 'REMOVE_PRICE_MIN';
export const REMOVE_PRICE_MAX = 'REMOVE_PRICE_MAX';
export const REMOVE_MILEAGE_MIN = 'REMOVE_MILEAGE_MIN';
export const REMOVE_MILEAGE_MAX = 'REMOVE_MILEAGE_MAX';






