export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_FAIL = 'ADDUSER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const GET_VEHICLES = 'GET_VEHICLES';
export const GET_VEHICLES_FAIL = 'GET_VEHICLES_FAIL';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const ADD_VEHICLE_FAIL = 'ADD_VEHICLE_FAIL';
export const REQUEST_USER_VEHICLES = 'REQUEST_USER_VEHICLES';
export const RECEIVE_USER_VEHICLES = 'RECEIVE_USER_VEHICLES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';





